DROP DATABASE IF EXISTS CUNG_CAP_XE;
CREATE DATABASE IF NOT EXISTS CUNG_CAP_XE;

USE CUNG_CAP_XE;

DROP TABLE IF EXISTS NHACUNGCAP;
CREATE TABLE IF NOT EXISTS NHACUNGCAP
(
	MANHACC	CHAR(6)	NOT NULL,
    TENNHACC	VARCHAR(20)	NOT  NULL,
    DIACHI	VARCHAR(50)	NOT NULL,
    SODT	CHAR(11)	NOT NULL,
    MASOTHUE	CHAR(6)	NOT NULL,
    PRIMARY KEY (MANHACC)
);

DROP TABLE IF EXISTS LOAIDICHVU;
CREATE TABLE IF NOT EXISTS LOAIDICHVU	
(
	MALOAIDV	CHAR(4)	NOT NULL,
    TENLOAIDICHVU	VARCHAR(30)	NOT NULL,
    PRIMARY KEY	(MALOAIDV)
);


DROP TABLE IF EXISTS MUCPHI;
CREATE TABLE IF NOT EXISTS	MUCPHI
(
	MAMP	CHAR(4)	NOT NULL,
    DONGIA	REAL	NOT NULL,
    MOTA	VARCHAR(20)		NOT NULL,
    PRIMARY KEY(MAMP)
);

DROP TABLE IF EXISTS DONGXE;
CREATE TABLE IF NOT EXISTS DONGXE
(
	DONGXE	VARCHAR(10)	NOT NULL,
    HANGXE	VARCHAR(7)	NOT NULL,
    SOCHONGOI	SMALLINT NOT NULL,
    PRIMARY KEY(DONGXE)
);

DROP TABLE IF EXISTS DANGKY;
CREATE TABLE IF NOT EXISTS DANGKY
(
	MADK	CHAR(5)	NOT NULL,
    MANHACC	CHAR(6)	NOT NULL,
    MALOAIDV	CHAR(4)	NOT NULL,
    DONGXE	VARCHAR(10)	NOT NULL,
    MAMP	CHAR(4)	NOT NULL,
    NGAYBATDAUCC	DATETIME	NOT NULL,
    NGAYKETTHUCCC	DATETIME	NOT NULL,
    SOLUONGDKXE		SMALLINT	NOT NULL,
    PRIMARY KEY(MADK),
    FOREIGN KEY(MANHACC) REFERENCES NHACUNGCAP(MANHACC),
    FOREIGN KEY(MALOAIDV)	REFERENCES	LOAIDICHVU(MALOAIDV),
    FOREIGN KEY(DONGXE)		REFERENCES	DONGXE(DONGXE),
    FOREIGN KEY(MAMP)		REFERENCES	MUCPHI(MAMP)
);

INSERT INTO	NHACUNGCAP(MANHACC,                 TENNHACC,    DIACHI,         SODT, MASOTHUE)
VALUES				  ( 'NCC001',     'CTY TNHH TOAN PHAP','HAI CHAU','05113999888', '568941'),
					  ( 'NCC002','CTY CO PHAN DONG DU','LIEN CHIEU','05113999889','456789'),
                      ('NCC003','NGUYEN VAN A','HOA THAN','05113999890','321456'),
                      ('NCC004','CTY TOANCAUXANH','HAI CHAU','05113658945','513364'),
                      ('NCC005','CTY TNHH AMA','THANH KHE','05113875466','546546'),
                      ('NCC006','TRAN THI BICH VAN','	LIEN CHIEU','05113587469','524545'),
                      ('NCC007','CTY TNHH PHAN THANH','THANH KHE','05113987456','113021'),
                      ('NCC008','PHAN DINH NAM','HOA THAN','05113351456','121230'),
                      ('NCC009','TAP DOAN DONG NAM A','LIEN CHIEU','05113987121','533654'),
                      ('NCC010','CTY RANG DONG','LIEN CHIEU','05113569654','187864');
                      
INSERT INTO LOAIDICHVU(MALOAIDV,TENLOAIDICHVU)
VALUES				  ('DV01','DICH VU TAXI'),
					  ('DV02','DICH VU XE BUS'),
                      ('DV03','DICH VU CHO THUE');
                      
INSERT INTO MUCPHI(MAMP, DONGIA,        MOTA)
VALUES			  ('MP01', 10.000,'AP DUNG TU 1/2015'),
				  ('MP02',15.000,'AP DUNG TU 2/2015'),
                  ('MP03',20.000,'AP DUNG 1/2010'),
                  ('MP04',25.000,'AP DUNG 2/2011');
                  
INSERT INTO DONGXE(DONGXE,HANGXE,SOCHONGOI)
VALUES	   		  ('HIACE','TOYOTA',16),
				  ('VIOS','TOYOTA',5),
                  ('ESCAPE','FORD',5),
                  ('CERATO','KIA',7),
                  ('FORTE','KIA',5),
                  ('STAREX','HUYNDAI',7),
                  ('GRAND-I10','HUYNDAI',7);
                  
/*INSERT INTO	DANGKY(  MADK,MANHACC,MALOAIDV,DONGXE,MAMP,NGAYBATDAUCC,NGAYKETTHUCCC,SOLUONGDKXE)
VALUES	*/		  


/*3*/

SELECT DONGXE,HANGXE,SOCHONGOI
FROM DONGXE
WHERE SOCHONGOI >5;

/*4*/

SELECT NCC.MANHACC,NCC.TENNHACC,NCC.DIACHI,NCC.SODT,NCC.MASOTHUE
FROM NHACUNGCAP NCC
JOIN DANGKY DK ON NCC.MANHACC=DK.MANHACC
JOIN MUCPHI MP ON DK.MAMP=MP.MAMP
JOIN DONGXE DX ON DK.DONGXE=DX.DONGXE
WHERE DX.HANGXE='TOYOTA' AND MP.DONGIA= 15.000
UNION
SELECT NCC.MANHACC,NCC.TENNHACC,NCC.DIACHI,NCC.SODT,NCC.MASOTHUE
FROM NHACUNGCAP NCC
JOIN DANGKY DK ON NCC.MANHACC=DK.MANHACC
JOIN MUCPHI MP ON DK.MAMP=MP.MAMP
JOIN DONGXE DX ON DK.DONGXE=DX.DONGXE
WHERE DX.HANGXE='KIA' AND MP.DONGIA=20.000;

/*5*/

SELECT TENNHACC,LENGTH(TENNHACC) AS LENGTHNAME
FROM NHACUNGCAP
ORDER BY LENGTH(TENNHACC);

SELECT CAST(MASOTHUE AS UNSIGNED) AS MASOTHUE
FROM NHACUNGCAP
ORDER BY MASOTHUE;

/*6*/

WITH RAW6 AS(
SELECT MANHACC
FROM DANGKY
WHERE NGAYBATDAUCC>'2015/11/20')
SELECT MANHACC,COUNT(MANHACC)
FROM RAW6
GROUP BY MANHACC;

/*7*/

SELECT DISTINCT HANGXE
FROM DONGXE;

/*8*/

SELECT DK.MADK,NCC.MANHACC,NCC.TENNHACC,NCC.DIACHI,NCC.MASOTHUE,DV.TENLOAIDICHVU,MP.DONGIA,DX.HANGXE,DK.NGAYBATDAUDK,DK.NGAYKETTHUCCC
FROM	NHACUNGCAP NCC
CROSS JOIN DANGKY DK ON NCC.MANHACC = DK.MANHACC
JOIN	MUCPHI MP ON MP.MAMP=DK.MAMP
JOIN    DONGXE DX ON DX.LOAIXE=DK.LOAIXE
JOIN LOAIDICHVU DV ON DV.MALOAIDICHVU=DK.MALOAIDICHVU; 






